apiVersion: apps/v1
kind: Deployment
metadata:
  name: developerhub-user-service
spec:
  selector:
    matchLabels:
      app: developerhub-user-service
  replicas: 1
  template:
    metadata:
      labels:
        app: developerhub-user-service
    spec:
      containers:
        - name: developerhub-user-service
          image: steven8519/developerhub-user-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: developerhub-user-service
spec:
  selector:
    app: developerhub-user-service
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080