apiVersion: apps/v1
kind: Deployment
metadata:
  name: developerhub-user-service
spec:
  selector:
    matchLabels:
      app: developerhub-user-service
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: developerhub-user-service
    spec:
      containers:
        - name: developerhub-user-service
          image: steven8519/developerhub-user-service:latest
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: developerhub-user-service
  ports:
    - name: http
      port: 8080
      nodePort: 30010

    - name: endpoint
      port: 61616

  type: NodePort